version: '3.7'

networks:
  laravel:

services:
  database:
    image: mysql:5.7.28
    container_name: database
    restart: 'no'
    volumes:
      - ./docker/database/mysql.cnf:/etc/mysql/my.cnf
      - ./docker/database/persist:/var/lib/mysql
      - ./docker/database/base.sql:/base.sql
    networks:
      - laravel
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: database
    command: --init-file /base.sql
    logging:
        driver: none

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ${APP_PATH:-./src}:/app
    working_dir: /app
    command: composer install

  node:
    image: node:lts
    container_name: node
    volumes:
      - ${APP_PATH:-./src}:/app
    working_dir: /app
    command: yarn install

  app:
    container_name: app
    restart: 'no'
    volumes:
      - ${APP_PATH:-./src}:/var/www
      - ./docker/app/entrypoint.sh:/entrypoint.sh
    networks:
      - laravel
    ports:
      - 9000:9000
    depends_on:
      - composer
      - node
    build:
      context: .
      dockerfile: ./docker/app/dockerfile
    entrypoint: /entrypoint.sh
    command: php-fpm

  webserver:
    image: nginx:stable
    container_name: webserver
    restart: 'no'
    volumes:
      - ${APP_PATH:-./src}:/var/www
      - ./docker/webserver/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    ports:
      - 8080:80
    depends_on:
      - database
      - app
